"""
Processes all data generated by the simulation with the `JSON_OUTPUT` exec method.
"""

import json
from itertools import zip_longest
from os import listdir, path

import numpy

files = (path.join("output/", f) for f in listdir("output/"))
files = (open(f, 'r', encoding='utf-8') for f in files if path.isfile(f))

data = [json.load(file)['average_satisfactions'] for file in files]

data_min = [min(point for point in line if point is not None) for line in zip_longest(*data)]
data_max = [max(point for point in line if point is not None) for line in zip_longest(*data)]
data_avg = [numpy.average([point for point in line if point is not None]) for line in zip_longest(*data)]

output = {
	"data_min": data_min,
	"data_max": data_max,
	"data_avg": data_avg,
}
output_file = open("output.json", 'w', encoding="utf-8")
json.dump(output, output_file)
